language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

env:
   global:
      - APP_KEY=WOZryj3ZBRIEAk5Az05rcnGXEhmIoRUW

install:
    - travis_retry composer install --no-interaction --prefer-source

before_script:
    - phpenv config-rm xdebug.ini || true

script:
    - vendor/bin/phpunit